[package]
name = "bmtui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29"
crossterm = { version = "0.28", features = ["event-stream"] }
tokio = { version = "1.42", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
rand = "0.8"
